// Generated by LiveScript 1.6.0
(function(){
  var pg, lderror, sessionStore, userStore, database;
  pg = require('pg');
  lderror = require('lderror');
  sessionStore = require('./session-store');
  userStore = require('./user-store');
  pg.defaults.poolSize = 30;
  database = function(backend, opt){
    var config, log, ref$, ref1$, user, password, host, database, port, poolSize;
    opt == null && (opt = {});
    this.config = config = backend.config;
    this.log = log = backend.log.child({
      module: 'db'
    });
    ref1$ = !config.db.postgresql.profile
      ? config.db.postresql
      : import$(import$({}, config.db.postgresql), ((ref$ = config.db.postgresql) != null ? ref$.profiles[config.db.postgresql.profile] : void 8) || {}), user = ref1$.user, password = ref1$.password, host = ref1$.host, database = ref1$.database, port = ref1$.port, poolSize = ref1$.poolSize;
    this.uri = "postgres://" + user + ":" + password + "@" + host + (port ? ':' + port : '') + "/" + database;
    this.pool = new pg.Pool({
      connectionString: this.uri,
      max: poolSize || 20,
      idleTimeoutMillis: 30000,
      connectionTimeoutMillis: 2000
    });
    this.pool.on('error', function(err, client){
      return log.error("db pool error".red);
    });
    this.sessionStore = new sessionStore({
      db: this,
      session: backend.config.session.maxAge,
      logger: log,
      queryOnly: opt.queryOnly
    });
    this.userStore = new userStore({
      db: this,
      config: config,
      logger: log
    });
    return this;
  };
  database.prototype = import$(Object.create(Object.prototype), {
    query: function(q, p){
      return this.pool.connect().then(function(client){
        return client.query(q, p).then(function(ret){
          client.release();
          return ret;
        });
      })['catch'](function(it){
        return Promise.reject(new lderror({
          err: it,
          id: 0,
          query: q,
          message: "database query error"
        }));
      });
    }
  });
  module.exports = database;
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
