// Generated by LiveScript 1.6.0
(function(){
  var fs, path, express, bodyParser, aux;
  fs = require('fs');
  path = require('path');
  express = require('express');
  bodyParser = require('body-parser');
  aux = require('./aux');
  module.exports = function(backend){
    var app, server;
    app = express();
    app.use(bodyParser.json());
    backend.route.localctl = aux.routecatch(app);
    backend.route.localctl.post('/cachestamp', function(req, res, next){
      return res.send((backend.cachestamp = new Date().getTime()) + "");
    });
    server = null;
    return {
      init: function(){
        return new Promise(function(res, rej){
          var sock, e;
          if (server) {
            return res();
          }
          sock = path.join(backend.root, '.localctl.sock');
          try {
            fs.unlinkSync(sock);
          } catch (e$) {
            e = e$;
            null;
          }
          return server = app.listen(sock, function(){
            var e;
            try {
              fs.chmodSync(sock, 384);
            } catch (e$) {
              e = e$;
              null;
            }
            backend.logServer.info("local control channel on " + sock);
            return res();
          });
        });
      }
    };
  };
}).call(this);
