// Generated by LiveScript 1.6.0
(function(){
  var lib;
  lib = require('@servebase/payment/lib');
  (function(it){
    return module.exports = it;
  })(function(backend){
    return lib({
      backend: backend
    });
  });
}).call(this);
