#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
rm -rf lib
mkdir -p dist/gateway/dummy/pay dist/gateway/dummy/paid
mkdir lib

bin=../../../node_modules/.bin
echo "build src/index.ls -> dist/index.js ..."
$bin/lsc -cp src/index.ls > dist/index.js
echo "minify dist/index.js -> dist/index.min.js ..."
$bin/uglifyjs dist/index.js > dist/index.min.js

echo "build gateway/pay/index.pug -> dist/gateway/pay/index.html ..."
$bin/srcbuild-pug src/gateway/dummy/pay/index.pug > dist/gateway/dummy/pay/index.html
echo "build gateway/paid/index.pug -> dist/gateway/paid/index.html ..."
$bin/srcbuild-pug src/gateway/dummy/paid/index.pug > dist/gateway/dummy/paid/index.html

echo "build server files ..."
$bin/lsc -cp src/lib/index.ls > lib/index.js
for n in dummy newebpay oen; do
  mkdir -p lib/$n
  $bin/lsc -cp src/lib/$n/index.ls > lib/$n/index.js
done
